version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: node_performance_postgresql
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
